### ISSUE TITLE
Add Row on Tab - Focus

### ISSUE THREAD

**Issue by RichardD2** [nCrafts/tabular-input#1]
Using Firefox 48, when you tab from the last cell in the "Add Row on Tab" example, the new row is added, but the focus moves to the first cell in the "Column Heads" example.

In Chrome 52, Opera 39, IE11 and Edge, the focus correctly moves to the first cell of the new row.

**Comment by nCrafts** [comment]
The row limit for the example is capped at 6. When the limit is reached, the browser behaviour kicks in and cursor moves to the next input field on the page.

The focus works correctly (first cell of new row) when rows are less than 6 and you hit tab.

**Comment by RichardD2** [comment]
That is **not** what's happening on your example:
https://ncrafts.github.io/tabular-input/
- Go to the "Add Row on Tab" example in Firefox. There are three rows.
- Tab out of the last cell.
- A new row is added.
- The focus moves to the first cell of the "Column Heads" example!

The example works perfectly in Chrome, IE11 and Edge. But in Firefox, the focus is **not** working correctly.

**Comment by RichardD2** [comment]
I've attached a video of the issue:
[TabularInput-Issue-1.zip](https://github.com/nCrafts/tabular-input/files/444694/TabularInput-Issue-1.zip)

**Comment by nCrafts** [comment]
Please have a look at the update. It should be working now.

**Comment by RichardD2** [comment]
That's working now, thanks. :)
